nDPI and other small updates

diff --git a/src/usr/lib/turtlefirewall/domain_blacklist b/src/usr/lib/turtlefirewall/domain_blacklist
--- a/src/usr/lib/turtlefirewall/domain_blacklist
+++ b/src/usr/lib/turtlefirewall/domain_blacklist
@@ -1,4 +1,9 @@
 #!/bin/bash
+#
+# Enable Auto Update with :
+# ln -sf /usr/lib/turtlefirewall/domain_blacklist /etc/cron.daily/domain_blacklist
+#
+
 echo -e "\nTurtle Firewall 2.2 - Domain Blacklist";
 echo -e "Copyright (c) 2001-2023 Andrea Frigido\n";
 
@@ -8,7 +13,8 @@ grep -E 'drop_domain_blacklist.*="on"|="on".*drop_domain_blacklist' $fw_file > /
 if [ $? = 0 ]
  then
 
-blacklist_file="/etc/turtlefirewall/domain_blacklist.dat"
+drop_blacklist_file="/etc/turtlefirewall/drop_domain_blacklist.dat"
+never_blacklist_file="/etc/turtlefirewall/never_domain_blacklist.dat"
 
 Help () {
  echo "Usage :  domain_blacklist [OPTION]"
@@ -76,18 +82,18 @@ echo -e "Download : \c"
 systemctl is-enabled turtlefirewall > /dev/null 2>&1
 if [ $? = 0 ]
  then
-   wget -q -O - https://threatfox.abuse.ch/downloads/hostfile \
-   | dos2unix \
-   | awk -F "\t" '(!/^#/ && $2~/^[A-z0-9\-\.]+$/){print $2}' \
-   | sort -u \
-   > $blacklist_file
-   if [ $? = 0 ]
-    then
-     echo -e "OK"
-   else
-     echo -e "FAIL"
-   fi
-  chmod 600 $blacklist_file
+  wget -q -O - https://threatfox.abuse.ch/downloads/hostfile \
+  | dos2unix \
+  | awk -F "\t" '(!/^#/ && $2~/^[A-z0-9\-\.]+$/){print $2}' \
+  | sort -u \
+  > $drop_blacklist_file
+  if [ $? = 0 ]
+   then
+    echo -e "OK"
+  else
+    echo -e "FAIL"
+  fi
+  chmod 600 $drop_blacklist_file
 else
   echo -e "turtlefirewall not enabled"
   echo
@@ -97,19 +103,29 @@ fi
 
 Import () {
 echo -e "Import : \c"
-if [ -s $blacklist_file ]
+if [ -s $drop_blacklist_file ]
  then
-   sed "s/^/drop_domain_blacklist:RISK_DOMAIN_/" $blacklist_file > /proc/net/xt_ndpi/host_proto
-   count=`wc -l < $blacklist_file`
-   if [ $? = 0 ]
-    then
-     echo -e "$count"
-   else
-     echo -e "FAIL"
-   fi
+
+  # Ensure exclude
+  if [ -s $never_blacklist_file ]
+   then
+    while read blacklist_exclude
+     do
+      sed -i "/^$blacklist_exclude$/d" $drop_blacklist_file
+    done < $never_blacklist_file
+  fi
+
+  #sed "s/^/drop_domain_blacklist:RISK_DOMAIN_/" $drop_blacklist_file > /proc/net/xt_ndpi/host_proto
+  sed "s/^/drop_domain_blacklist:/" $drop_blacklist_file > /proc/net/xt_ndpi/host_proto
+  count=`wc -l < $drop_blacklist_file`
+  if [ $? = 0 ]
+   then
+    echo -e "$count"
+  else
+    echo -e "FAIL"
+  fi
  else
-   echo "drop_domain_blacklist:RISK_DOMAIN_dummy.tfw" > /proc/net/xt_ndpi/host_proto
-   echo -e "$blacklist_file empty"
+  echo -e "$drop_blacklist_file empty"
 fi
 }
 
diff --git a/src/usr/lib/turtlefirewall/ja3_blacklist b/src/usr/lib/turtlefirewall/ja3_blacklist
--- a/src/usr/lib/turtlefirewall/ja3_blacklist
+++ b/src/usr/lib/turtlefirewall/ja3_blacklist
@@ -1,4 +1,9 @@
 #!/bin/bash
+#
+# Enable Auto Update with :
+# ln -sf /usr/lib/turtlefirewall/ja3_blacklist /etc/cron.daily/ja3_blacklist
+#
+
 echo -e "\nTurtle Firewall 2.2 - JA3 Blacklist";
 echo -e "Copyright (c) 2001-2023 Andrea Frigido\n";
 
@@ -8,7 +13,8 @@ grep -E 'drop_ja3_blacklist.*="on"|="on".*drop_ja3_blacklist' $fw_file > /dev/nu
 if [ $? = 0 ]
  then
 
-blacklist_file="/etc/turtlefirewall/ja3_blacklist.dat"
+drop_blacklist_file="/etc/turtlefirewall/drop_ja3_blacklist.dat"
+never_blacklist_file="/etc/turtlefirewall/never_ja3_blacklist.dat"
 
 Help () {
  echo "Usage :  ja3_blacklist [OPTION]"
@@ -80,15 +86,15 @@ if [ $? = 0 ]
    | dos2unix \
    | awk -F "," '(!/^#/ && $1~/^[a-z0-9]{32}$/){print $1","$4}' \
    | sort -u \
-   > $blacklist_file
+   > $drop_blacklist_file
    if [ $? = 0 ]
     then
      echo -e "OK"
    else
      echo -e "FAIL"
    fi
-  chmod 600 $blacklist_file
-else
+  chmod 600 $drop_blacklist_file
+ else
   echo -e "turtlefirewall not enabled"
   echo
   exit 1
@@ -97,18 +103,29 @@ fi
 
 Import () {
 echo -e "Import : \c"
-if [ -s $blacklist_file ]
+if [ -s $drop_blacklist_file ]
  then
-   sed "s/,.*//;s/^/drop_ja3_blacklist:RISK_JA3_/" $blacklist_file > /proc/net/xt_ndpi/host_proto
-   count=`wc -l < $blacklist_file`
-   if [ $? = 0 ]
-    then
-     echo -e "$count"
-   else
-     echo -e "FAIL"
-   fi
+
+  # Ensure exclude
+  if [ -s $never_blacklist_file ]
+   then
+    while read blacklist_exclude
+     do
+      sed -i "/^$blacklist_exclude$/d" $drop_blacklist_file
+    done < $never_blacklist_file
+  fi
+
+  sed "s/,.*//;s/^/drop_ja3_blacklist:RISK_JA3_/" $drop_blacklist_file > /proc/net/xt_ndpi/host_proto
+  #sed "s/,.*//;s/^/drop_ja3_blacklist:JA3C_/" $drop_blacklist_file > /proc/net/xt_ndpi/host_proto
+  count=`wc -l < $drop_blacklist_file`
+  if [ $? = 0 ]
+   then
+    echo -e "$count"
+  else
+    echo -e "FAIL"
+  fi
  else
-   echo -e "$blacklist_file empty"
+  echo -e "$drop_blacklist_file empty"
 fi
 }
 
