Theme : Standardize Webmin images.

diff --git a/src/usr/lib/turtlefirewall/ip_blacklist b/src/usr/lib/turtlefirewall/ip_blacklist
--- a/src/usr/lib/turtlefirewall/ip_blacklist
+++ b/src/usr/lib/turtlefirewall/ip_blacklist
@@ -73,31 +73,29 @@ echo -e "Download : \c"
 systemctl is-enabled turtlefirewall > /dev/null 2>&1
 if [ $? = 0 ]
  then
-   result="1"
-   wget -q -O - https://sslbl.abuse.ch/blacklist/sslipblacklist.txt \
-    | dos2unix \
-    | awk '(!/^#/ && $1~/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$/){print $1}' \
-    | sort -u \
-    > $drop_blacklist_file
-   [ $? = 0 ] && result=0
-   wget -q -O - https://feodotracker.abuse.ch/downloads/ipblocklist_recommended.txt \
-    | dos2unix \
-    | awk '(!/^#/ && $1~/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$/){print $1}' \
-    | sort -u \
-    >> $drop_blacklist_file
-   [ $? = 0 ] && result=0
-   wget -q -O - https://lists.blocklist.de/lists/all.txt \
-    | dos2unix \
-    | awk '(!/^#/ && $1~/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$/){print $1}' \
-    | sort -u \
-    >> $drop_blacklist_file
-   [ $? = 0 ] && result=0
-   if [ $result = 0 ]
-    then
-     echo -e "OK"
-   else
-     echo -e "FAIL"
-   fi
+  result="1"
+  wget -q -O - https://sslbl.abuse.ch/blacklist/sslipblacklist.txt \
+   | dos2unix \
+   | awk '(!/^#/ && $1~/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$/){print $1}' \
+   > $drop_blacklist_file
+  [ $? = 0 ] && result=0
+  wget -q -O - https://feodotracker.abuse.ch/downloads/ipblocklist_recommended.txt \
+   | dos2unix \
+   | awk '(!/^#/ && $1~/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$/){print $1}' \
+   >> $drop_blacklist_file
+  [ $? = 0 ] && result=0
+  wget -q -O - https://lists.blocklist.de/lists/all.txt \
+   | dos2unix \
+   | awk '(!/^#/ && $1~/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$/){print $1}' \
+   >> $drop_blacklist_file
+  [ $? = 0 ] && result=0
+  if [ $result = 0 ]
+   then
+    echo -e "OK"
+  else
+    echo -e "FAIL"
+  fi
+  sort -u $drop_blacklist_file -o $drop_blacklist_file
   chmod 600 $drop_blacklist_file
 else
   echo -e "turtlefirewall not enabled"
diff --git a/src/usr/lib/turtlefirewall/sha1_blacklist b/src/usr/lib/turtlefirewall/sha1_blacklist
--- a/src/usr/lib/turtlefirewall/sha1_blacklist
+++ b/src/usr/lib/turtlefirewall/sha1_blacklist
@@ -85,14 +85,14 @@ if [ $? = 0 ]
   wget -q -O - https://sslbl.abuse.ch/blacklist/sslblacklist.csv \
    | dos2unix \
    | awk -F "," '(!/^#/ && $2~/^[a-z0-9]{40}$/){print $2}' \
-   | sort -u \
    > $drop_blacklist_file
-   if [ $? = 0 ]
-    then
-     echo -e "OK"
-   else
-     echo -e "FAIL"
-   fi
+  if [ $? = 0 ]
+   then
+    echo -e "OK"
+  else
+    echo -e "FAIL"
+  fi
+  sort -u $drop_blacklist_file -o $drop_blacklist_file
   chmod 600 $drop_blacklist_file
 else
   echo -e "turtlefirewall not enabled"
